### ISSUE TITLE
Enhancement: Factions

### ISSUE THREAD

**Issue by Thiana** [Funwayguy/StandardQuestingPack#10]
Could you please consider adding support for factions similar to HQM? 

Task: Check for a particular reputation value with a faction.
Reward: Modify the reputation with a faction.

Thank you.

**Comment by Funwayguy** [comment]
Use scoreboard tasks/rewards. They can do much more than the old Faction system.

EDIT: What exactly are you trying to do with 'factions' that you believe scoreboards can't achieve?
