### ISSUE TITLE
Division by zero crash after opening loot chest...

### ISSUE THREAD

**Issue by wojoeraf** [Funwayguy/StandardQuestingPack#101]
https://paste.dimdev.org/vuxikehihe.mccrash

**Comment by Funwayguy** [comment]
Already fixed in Standard Expansion 3.4.172

**Comment by wojoeraf** [comment]
Thanks a lot for the info.
I try to reach out to the creator of the "Engineer's Life" modpack for this information so he can update to the latest version of your mod.

**Comment by wojoeraf** [comment]
I updated my local singleplayer world with the newest version of your mod.
The error is gone but the loot chests always says NULL on opening...
