### ISSUE TITLE
[1.12.2]How do I add items to the reward box?

### ISSUE THREAD

**Issue by Cinnaio** [Funwayguy/StandardQuestingPack#103]
When I try to open Loot Chests, the pop-up GUI shows "No Loot Setup", but when I open nbt as "Loot Drop" is valid, so I want to ask how to solve it?
My English level is not too high, so I use Google Translate. Thank you
![no loot setup](https://user-images.githubusercontent.com/61103710/74599859-c4462e80-50c3-11ea-9c8b-373d49da85c9.png)

**Comment by Cinnaio** [comment]
@Funwayguy

**Comment by Cinnaio** [comment]
I am so sorry, but I need your help very much. Thank you.

**Comment by Cinnaio** [comment]
Sorry, due to my mistake, and then overlooked something, the problem has been solved now, thank you.

**Comment by Funwayguy** [comment]
I completely missed this today, sorry. In future if you just need help with making something there is a Discord link on the curseforge page. There are a number of people there that can more readily help you out there, including me.
