### ISSUE TITLE
1.7.10 Can't view (R) NEI recipies game crashes.

### ISSUE THREAD

**Issue by mindcloud69** [Funwayguy/StandardQuestingPack#12]
I have tried this with versions 1.0.52-59 it crashes with all of them.

[https://gist.github.com/mindcloud69/a1257d280dc31f8aa540e1fa53b2c108](https://gist.github.com/mindcloud69/a1257d280dc31f8aa540e1fa53b2c108)

**Comment by Dream-Master** [comment]
your log shows Version 52.

**Comment by Funwayguy** [comment]
BetterQuesting 1.0.89 and Standard Expansion 1.0.59 should work just fine together. If you have a crash log with those two versions or newer post that log.

**Comment by Dream-Master** [comment]
For me it works on the client but i not test it on my server yet.

**Comment by Dream-Master** [comment]
works on servers too. Forgot to mention this here :)
