### ISSUE TITLE
Crashes when creating "block breaking" tasks

### ISSUE THREAD

**Issue by trollusk** [Funwayguy/StandardQuestingPack#15]
When creating a block breaking task, the first data field is a free text field for "block ID". If this is left blank or the name of a nonexistent block is entered, then on exiting the editor, the quest shows a blank icon for the block to break, and the game immediately crashes.

This also seems to happen if an oredict entry is given as the block ID, e.g. OreDict:oreTin.

**Comment by Funwayguy** [comment]
Can't seem to recreate this on any current build so I'm marking this as fixed.
