### ISSUE TITLE
Game crashing on launch

### ISSUE THREAD

**Issue by ziadbenaman** [Funwayguy/StandardQuestingPack#18]
I'm using the latest version of StandardExpansion and BetterQuesting , the game was crashing everytime when loading .
here is the crash report : 
[crash-2016-08-02_18.21.25-client.txt](https://github.com/Funwayguy/StandardQuestingPack/files/397742/crash-2016-08-02_18.21.25-client.txt)

thanks

**Comment by Funwayguy** [comment]
You installed the deobfuscated developer version of Standard Expansion, please try again with the correct version.

**Comment by ziadbenaman** [comment]
Ok thank you
