### ISSUE TITLE
Question: Editing the pre-defined loot chests

### ISSUE THREAD

**Issue by Drethic** [Funwayguy/StandardQuestingPack#2]
Where can you edit the pre-defined loot chests that are added by the Standard Questing Pack?  I looked in the saves/<saved game>/QuestLoot.json file and only found this:

```
{
  "groups": []
}
```

Is there a command to edit them?  I tried right clicking with the shiny edit loot chest and brings up a list but there are no items contained in the list.

**Comment by Funwayguy** [comment]
I'm writing a proper editor for it in the next update. It's hard to explain the formatting but it's a list of weighted loot groups and then another layer of weighted entries. If there is no default loot data setup then it defaults to the dungeon loot drop table. In the mean time while you wait for me to finish the editor, here's an example of what a loot import from Agrarian Skies looks like in Better Questing: http://pastebin.com/9GYDzf44

**Comment by Drethic** [comment]
Does this sound right for the different parts within a group?  I made some assumptions based on how the data was structured.

Within the groups array you need to add an object with the following elements:
```
"name" (string) The name of this group
"weight" (int) What types of items the group should have, the lower the number the more common or less valuable
"rewards"(array) An array of objects containing the following elements:
	"weight" (int) How often the reward object should be chosen, the higher the number the more often that reward object will be chosen
	"items" (array) An array of objects that are randomly choosen from containing the following elements:
		"id" (string) The ore dictionary name for the item
		"Count" (int) How many the player should receive when chosen
		"Damage" (int) How much damage an item should take, or the meta data number for the item
```

**Comment by Funwayguy** [comment]
That is mostly correctexcept for two things:
- 'name' can also be localised with resource packs
- any entries inside the 'items' list are actually NBT representations of an item stack (see http://minecraft.gamepedia.com/Item_%28entity%29/ED under the entity's 'Item' tag) and will be parsed as such.
- 'count' to be more accurate is the item's stack size.

You won't really need to worry about the specifics of all this once I've finished the editor but feel free to make rewards this way. You should be able to fix up any past mistakes with the editor anyway

**Comment by Drethic** [comment]
The new loot group editor works great!

Along those lines, is there a way to disable the Dungeon Loot group so that the rarity percentage chests stick closer to the groups I've defined based on weights of 1 (Basic / Rarity 0%), 25 (Common / Rarity 25%), 50 (Uncommon / Rarity 50%), 75 (Rare / Rarity 75%), 100 (Legendary / Rarity 100%)?

**Comment by Funwayguy** [comment]
Although not officially documented anywhere yet, that already happens internally. There's only a 25% weight tolerance meaning a 0% luck chest will only get the lower 25% of drops and 100% luck chest will only give you the upper 25%. Where those percent boundries lie is dependent on the loot group weight distributions.

**Comment by Drethic** [comment]
It's seems to work most of the time.  However, I have a couple item groups setup within my Basic weight of 1 and at least half of the chests I've opened ( stored them up like someone who would do a few quests then open the loot all at once ) has triggered from the Dungeon Loot group ( not set by me ) instead of the basic one.  Because that's adding a lot of higher end items I'd like to disable that, or find a group configuration that will keep it from popping up.

**Comment by Funwayguy** [comment]
The Dungeon Loot fallback group should only show up if there is a group with no items/entries. Seems there might be something broken in the background or the editor isn't setting them properly.

**Comment by Drethic** [comment]
Here is a copy of my QuestLoot.json

http://pastebin.com/cEQSDyUm

Can I set the Basic group weight to 0?  There might be a small enough margin between weight 0 and 1 to cause Dungeon Loot to trigger now and then.

**Comment by Funwayguy** [comment]
I think I know what's screwing up now but I'm not at my computer at the moment and won't be able to fix it till tomorrow. I don't have any work arounds for it right now either. Also I'm not sure if setting the value to 0 will work because it's prevented in code.
