### ISSUE TITLE
[Suggestion] : Scoreboard Commands

### ISSUE THREAD

**Issue by CaiganMythFang** [Funwayguy/StandardQuestingPack#21]
There doesn't seem to be an easy way to handle Scoreboard (reputation) things, both in displaying current Scoreboard, or manipulating values.

This is important for questbooks that have repeatable quests for scoreboard, or quests that use scoreboard to track 'currency'.

I would suggest, if possible, a set of commands like : 
/bq_admin scoreboard [show | set] [player] [all | "scoreboard name"] [value]

Examples : 
/bq_admin scoreboard show caigan all
Would print into chat all of player "caigan" 's various scoreboard values.

/bq_admin scoreboard set caigan "Job Reputation" 300
Would set Job Reputation for caigan to 300

In addition, an easy way to show a player's Scoreboard listings in the Better Questing interface would be helpful as well.

**Comment by Funwayguy** [comment]
Scoreboards are a vanilla function and have their own commands and display options.
