### ISSUE TITLE
Creating a block breaking quest then returning to the main screen crashes client

### ISSUE THREAD

**Issue by Gamerbolts** [Funwayguy/StandardQuestingPack#23]
Hi not sure what happened, but I crashed while doing a standardexpansion block breaking quest. Maybe it's because I named the block incorrectly to break? Here is the error log http://pastebin.com/T0ke9qyA

**Comment by Gamerbolts** [comment]
Crashes me every time I go back to that quest

**Comment by Funwayguy** [comment]
I sent a bug fix out for this already but it seems the 1.7.10 build failed. I'll try and get that fixed sometime today

**Comment by Gamerbolts** [comment]
awesome, thank you
