### ISSUE TITLE
[1.10.2] Crash on world creation or join (2.3.114)

### ISSUE THREAD

**Issue by xSparky911x** [Funwayguy/StandardQuestingPack#35]
Crash log here -> http://pastebin.com/fJGd5AXZ

Using Forge 12.18.3.2185
Using Better Questing 1.3.180

If I use BQ - SE 1.3.92 everything is fine

**Comment by Funwayguy** [comment]
1.x.x builds are not compatible with 2.x.x expansions (Curse is mixing beta and release)
