### ISSUE TITLE
[1.10.2] Item detection - Toast

### ISSUE THREAD

**Issue by xSparky911x** [Funwayguy/StandardQuestingPack#36]
I added a crafting task for Toast, from Pam's HarvestCraft, set the required items to 3. BQ is not detecting the toast in the player's inventory. I have tried with and without ore dictionary name (foodToast). I have also tried a retrieval task as well.

BQ Version 1.3.180
BQ Standard Version - 1.3.92
Forge 2185

**Comment by Funwayguy** [comment]
I've stopped support for any 1.x.x builds of BetterQuesting. You'll need to update and try again

**Comment by xSparky911x** [comment]
Ok will do

**Comment by xSparky911x** [comment]
Confirmed, the updated versions fixed this issue
