### ISSUE TITLE
Enhancement: Add a variable to echo out the current key bind for the quest book

### ISSUE THREAD

**Issue by Drethic** [Funwayguy/StandardQuestingPack#4]
Due to other mods having similar key binds, if we have to change from the default key we would like to echo it out to the user as part of the command reward so they know how to access the book.  This will make porting quests around easier so we don't have to find/replace on the json file.

**Comment by Funwayguy** [comment]
This could be done yes but I don't see this as being a critically necessary feature nor is it specifically related to questing. I'll consider it but I make no guarantees

**Comment by Drethic** [comment]
That's understandable, if it's alright I can try making a small expansion that will add this function plus some other ones I'd like to see.  Do you have any recommendations for tutorials that cover developing mod addons?  I've only done basic mod work thus far.

**Comment by Funwayguy** [comment]
If you want to make an Expansion then by all means go for it. I can only suggest using Standard Expansion as an example because of how new the mod is. To get started you will need to download and include the deof jar in your dev workspace
