### ISSUE TITLE
[1.10.2] Adding items to a list has to be done twice

### ISSUE THREAD

**Issue by xSparky911x** [Funwayguy/StandardQuestingPack#40]
Forge 2185
BQ - Standard Expansion 2.3.116

Adding items to a list has to be done twice to update the name from stone to what ever you add.
For example I am adding a retrieval task. I add Iron Ore (16) to the list and click the "Done" button. It shows Stone as the item still. I go back in to edit the item but it is already showing it as Iron Ore (16). I click "Done" again and the item name is updated in the list.

**Comment by Funwayguy** [comment]
Fixed in BetterQuesting 2.0.202 and 2.3.203
