### ISSUE TITLE
[1.10.2] Retrieval Task Not Working - Fully

### ISSUE THREAD

**Issue by xSparky911x** [Funwayguy/StandardQuestingPack#41]
Trying to have the player collect different types of ores (16 of each certain type) but it still shows as incomplete after getting all the required ore. Also tried cheating the items in. Tried changing the task to retrieve Gold Ingots instead but I'm sure that would be better suited as a crafting task. (it didn't work either).

Am I doing something wrong or is this feature broken? I used the retrieval task for gathering wheat which seemed to work just fine.

**Comment by Funwayguy** [comment]
Did you have all the ores in your inventory at the time. Retrieval tasks currently require you to have all of the required items on you to complete the task (I will probably be changing this in future)

**Comment by xSparky911x** [comment]
Confirmed it works with all the items.
Feature request (if possible) Detect the items if in backpacks? Or is that even possible?

**Comment by Funwayguy** [comment]
I could potentially detect backpack contents but there's two problems with that:
1) It would only work in 1.10.2+
2) Only bags using Forge capabilities would be supported

**Comment by xSparky911x** [comment]
I am currently using forestry backpacks. Do they use Forge capabilities?

**Comment by Funwayguy** [comment]
According to the 1.10 branch on their GitHub, it does not include support for inventory capabilities through the item. So even if I was to try and implement it, Forestry would not be one of the supported backpacks.

**Comment by xSparky911x** [comment]
Ok thank you :)
