### ISSUE TITLE
[1.7.10] 2.0.121 Crash on TaskHunt.onKilledByPlayer

### ISSUE THREAD

**Issue by Psithief** [Funwayguy/StandardQuestingPack#43]
```
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at bq_standard.tasks.TaskHunt.onKilledByPlayer(TaskHunt.java:129)
	at bq_standard.handlers.EventHandler.onEntityKilled(EventHandler.java:77)
```

It looks like it's possible for EntityList.getEntityString to return null even if entity is valid,

https://github.com/Funwayguy/StandardQuestingPack/blob/1.7.10/src/main/java/bq_standard/tasks/TaskHunt.java#L129

**Comment by Funwayguy** [comment]
What entity did you kill? Looks like someone hasn't registered their entities correctly (then again I suppose I should add failsafe handling for mods doing silly things)

**Comment by Psithief** [comment]
It happened after I installed the Damage Indicators mod, raising the question whether the numbers it displays are somehow entities that can die. :unamused: 
Other possibilities:
* Ghost from RandomThings
* Some unseen entity from ExtraPlanets
* Maybe a crossbow bolt from Tinkers' Contruct

**Comment by zzyzzyzzx** [comment]
I get this also on project ozone 2:

only happens to us with tinkers weapons (bolts/throwing knives) while killing other players, and only while killing other players

**Comment by primetoxinz** [comment]
Can confirm this is still happening with version 2.1.0 on project ozone 2 with the same conditions as stated by @zzyzzyzzx http://www.termbin.com/0cuy

**Comment by Funwayguy** [comment]
Should be fixed now both for players and unregistered entities. Thanks for the reports.
