### ISSUE TITLE
Loot Chest JSON

### ISSUE THREAD

**Issue by 016Nojr** [Funwayguy/StandardQuestingPack#62]
Where is the json with the Loot chest configurations stored?

**Comment by Funwayguy** [comment]
Unless you've saved the loot JSON as the default, it should be located in the world directory under `QuestLoot.json`

If you're looking for the default loot file, that would be in `/config/betterquesting/DefaultLoot.json`

**Comment by 016Nojr** [comment]
Can I take the `QuestLoot.json` in the world directory, rename it to `DefaultLoot.json` and put it in `/config/betterquesting/` and make that the default loot in the pack?

**Comment by 016Nojr** [comment]
@Funwayguy not sure if you see this since you closed it

**Comment by Funwayguy** [comment]
There's a command that can do that for you. It should be something like:

`/bqs_admin default` 
or
`/bqs_loot`

Not at the computer at the moment to check

**Comment by 016Nojr** [comment]
Will try that, thanks.
It was `/bq_loot default save`
