### ISSUE TITLE
Experience rewards levels give always 0 to x level experience and not precise experience levels

### ISSUE THREAD

**Issue by Insane96** [Funwayguy/StandardQuestingPack#66]
E.g. At 10 levels, if I claim an experience reward that gives me 10 levels, I will not end up to level 20 but ~level 17.

**Comment by Funwayguy** [comment]
Not actually a bug. It does gives you 10 levels worth of XP but it's not relative to the player's current level. This way it keeps it fair to everyone in the party.

**Comment by Insane96** [comment]
Seems fair. Thanks for clarifying
