### ISSUE TITLE
Cant open the loot chest editor

### ISSUE THREAD

**Issue by 016Nojr** [Funwayguy/StandardQuestingPack#68]
Cant open the loot chest editor in game, tried making a new world, but it does not open.

Versions:
Forge: 14.23.4.2708
Better Questing: 3.5.259
Better Questing Standard Expansion: 3.4.143
Better Questing Triggerer (If it matters): 1.0

**Comment by ghost** [comment]
You need to make sure you have edit mode turn on as I just ran into that

**Comment by 016Nojr** [comment]
Idk, I fixed it some way back then, forgot about this issue
