### ISSUE TITLE
When printing the title of a scoreboard task, the text is centered as though it is printing the score name, not the display name.

### ISSUE THREAD

**Issue by talonos2** [Funwayguy/StandardQuestingPack#71]
To reproduce:

Have a scoreboard task where you check for the score name "Tiny", but the display name is "A very long name". You will see that the name extends off the right side of the screen, and is not centered at all.

To fix:

It's probably as easy as changing GuiTaskScoreboard.java line 40 to `int tw1 = mc.fontRenderer.getStringWidth(TextFormatting.BOLD + task.scoreDisp);` to match what is actually printed in the line beneath it.

**Comment by talonos2** [comment]
![image](https://user-images.githubusercontent.com/3359830/44016217-6ba039dc-9e91-11e8-8991-4ee2e3c7b957.png)

**Comment by Funwayguy** [comment]
Looks like when I changed it to use the display name instead I forgot to change the math to account for that. Thanks for the report, I'm a bit sidetracked working on another mod but I'll see about working this fix into the next set of BQ3 updates

**Comment by talonos2** [comment]
No prob. As always, thanks for your work.

**Comment by Funwayguy** [comment]
Sent up build 144 to CurseForge with this fix included.
