### ISSUE TITLE
Code derivation permission request

### ISSUE THREAD

**Issue by lawremi** [Funwayguy/StandardQuestingPack#72]
I've privately developed an NEI plugin for HQM (1.7.10) that derives its rendering code from the Better Questing NEI integration. Would you please grant permission for me to release the plugin publicly? I'm happy to cite your work in whatever way you desire.

**Comment by Funwayguy** [comment]
But doesn't HQM have native NEI support anyway? The reason I added it to BQ was _because_ HQM originally had it.

**Comment by lawremi** [comment]
The only NEI integration HQM has is that you can click on an ItemStack icon in the quest book to get the recipe or usage. It doesn't have the reverse, i.e., an NEI plugin that accesses the quest book. Or at least, I've never seen that, nor can I find any code for it.

Btw, my plugin goes beyond BQ in that it also supports tasks (usage), not just rewards (recipe).

**Comment by Funwayguy** [comment]
I think I forgot to approve this, but yes you can use it for HQM. Just don't use the BQ textures. BQ3 barely even uses that rendering code anymore anyway (it had issues).
