### ISSUE TITLE
conflict Climate Control ??

### ISSUE THREAD

**Issue by SvEgiiVEteR** [Funwayguy/StandardQuestingPack#8]
server
world hangs long and generated
creates a lot of files * .mca

I remove one of the mods
Climate Control-0.5.beta47.jar
or
StandardExpansion-1.0.19.jar
and the world load and only 10 files
how is this possible?
your mod does not participate in the generation of the world?

log
https://gist.github.com/anonymous/8eeab9bf7e121ad7e72b

**Comment by Funwayguy** [comment]
Standard Expansion doesn't even add anything to Minecraft directly other than a loot chest item. It's purely a task/reward/importer add-on for Better Questing and has no influence on how a world should be loading or what is in it.

On a side note, the log you've included is the FML debug log which isn't too helpful with this issue.
