### ISSUE TITLE
StandardExpansion-3.4.148.jar reports @VERSION@

### ISSUE THREAD

**Issue by Xetaxheb** [Funwayguy/StandardQuestingPack#81]
Trying Madpack 4, updated my mods manually through twitch launcher and got 148; CedQuestTracker-1.12.2-0.12.1.jar requires 145+ but apparently standardexpansion is reporting @VERSION@ instead of a real version.

**Comment by Funwayguy** [comment]
That's my bad. Messed up one of my build scripts. Already fixed for build 149 when that's ready for release
