### ISSUE TITLE
crafting tasks broken after update

### ISSUE THREAD

**Issue by charlescannon** [Funwayguy/StandardQuestingPack#82]
Updated from, spacing exact version, but it was released in August, to the 3.4.149 version, and none of my crafting tasks are being triggered when item is crafted.

**Comment by Funwayguy** [comment]
Hmm... double checked and I think I may have made a slight oversight (not quite a bug).
On the new task panel do you see the new row of icons above the list of requirements? That should tell you which methods are enabled to trigger the task. Unfortunately I forgot to set the defaults for loading existing crafting tasks and they all would likely default to disabled. In this case the task isn't exactly broken, just inert and in need of a quick reconfigure.

If you have a backup copy of the database before the update (BQ usually makes these for you), after I fix this up on my end, you can reload that copy and have the crafting tasks automatically load in with the proper defaults again without having to do the reconfigurations by hand.

**Comment by charlescannon** [comment]
Whoops forget to reply. Yep, looking into it that is what is happening. 

Anyways luckily it is like 4 quests that are crafting so it is a quick fix to do it manually, and I already have the fixed version up.

I originally dismissed the icons not knowing what they were for and just updated. Would've alerted you sooner if I actually bothered to playtest my modpack after updating instead of waiting a few days.

**Comment by Funwayguy** [comment]
No problem. I'll mark this as closed seeing as you've already fixed your end and I've fixed mine
