### ISSUE TITLE
crash after closing Themes

### ISSUE THREAD

**Issue by HSavageheart** [Funwayguy/StandardQuestingPack#83]
so i crash when i close th themes selection in the mod here is the crashlog and the video proof
https://pastebin.com/1uizmytd

with standart expansion
https://streamable.com/y4ulj

without
https://streamable.com/y93j2

**Comment by Funwayguy** [comment]
Your versions of BQ mods and expansions are all over the place. No wonder it's crashing.

The latest version of the base mod is 3.5.291 but yet you're running 3.5.288.

QuestBook appears to be a build meant for an experimental test version of BQ not for general use.

Standard Expansion is up to date but that's expecting the others to be somewhat up to date as well.

Update your mods and that should resolve your issue.
