### ISSUE TITLE
Console flood

### ISSUE THREAD

**Issue by Broculos** [Funwayguy/StandardQuestingPack#84]
The mod is giving error of the following errors:

![Screenshot_1](https://user-images.githubusercontent.com/46003804/54878771-21405280-4e29-11e9-8305-f696cc3d36d7.png)

**Comment by Funwayguy** [comment]
Whoops, accidentally left in some debugging code it seems. I'll see if I can get a build out tomorrow to remove that. It's nothing to be worried about though, I was just checking some crafting events were firing correctly while resolving those progression issues.
