### ISSUE TITLE
Crash when editing meeting mob

### ISSUE THREAD

**Issue by BlueYoshi68** [Funwayguy/StandardQuestingPack#85]
#121 Anatoli001
View User Profile
Send Message
Posted 12 mins ago
So my game crashes when i try and make a meeting event and change the mob. What should I do?

 

The game crashed whilst updating screen events
Error: java.lang.NoSuchFieldError: EDIT_NBT

 

Update: New Error, same reason.

The game crashed whilst updating screen events
Error: java.lang.NoSuchFieldError: EDIT_ENTITY

**Comment by Funwayguy** [comment]
Are you using the current version of both Better Questing and Standard Expansion? Those errors would only occur if one of those is out of date.

**Comment by BlueYoshi68** [comment]
Yeah sorry, i forgot to delete this. I figured out that i was 1 version behind shortly after....and it was the 1 version i needed lol.
