### ISSUE TITLE
removing quest numbers

### ISSUE THREAD

**Issue by BlueYoshi68** [Funwayguy/StandardQuestingPack#86]
There always seems to be a number at the end of my quest name that shows the order in which i made it, can i hide that?

**Comment by Funwayguy** [comment]
That's the quest ID, not the order. Only shows up if you have Advanced Tooltips enabled by pressing `F3 + H`. Not a bug and is intended if you need to use the ID in a command.

**Comment by BlueYoshi68** [comment]
thank you
