### ISSUE TITLE
[Suggestion]biome and structure quests and a question

### ISSUE THREAD

**Issue by stefanovich123** [Funwayguy/StandardQuestingPack#87]
I want biomes and structures quests like for example if you enter a biome or structure you completed a quest or if you kill an enemy in this biome.
If you plan to do this then thank you because it is a feature that will be very useful.
And a simple question.
If I am going to the jar file of betterquesting and change the png title screen to my own title screen am I not allowed to post my modpack on curseforge even if i give credit to you

**Comment by Funwayguy** [comment]
Soon...

https://github.com/Funwayguy/StandardQuestingPack/blob/1.12/src/main/java/bq_standard/tasks/TaskLocation.java#L36

Why would you be editing the JAR for the title page? If you're in edit mode you can just click the gear in the top left corner and customise it that way.

**Comment by stefanovich123** [comment]
Amazing!
Oh and about the jar file I looked back at it and the title screen turned back to default and it finally found the path of my title screen.
Why did I want to change it?
Well because before I always got a black and purple screen when I tried to change it in the config but that is not the case anymore.
And again thank you very much.
And now that we are talking about locations, will it work with dimensions too?

**Comment by Funwayguy** [comment]
Dimension support in location tasks has been supported since they were first made. These new biome and structure options can be applied in combination with the other existing ones.

EDIT: Closing this as all the work for the request is long since done. Just working on finishing some other stuff before I can get around to releasing it.

**Comment by stefanovich123** [comment]
Cool
