### ISSUE TITLE
Fluid retrieval quest not working

### ISSUE THREAD

**Issue by mobehun** [Funwayguy/StandardQuestingPack#9]
When I try to create a Fluid retrieval quest I always get this Item Placeholder thing.
![screenshot_20160411171922](https://cloud.githubusercontent.com/assets/8471727/14432630/3acb56ce-000b-11e6-9626-04894557fcf0.png)

BetterQuesting-1.1.77
StandardExpansion-1.1.46

**Comment by Funwayguy** [comment]
Can you post a screenshot of the raw NBT editor values?

**Comment by mobehun** [comment]
Yes, of course. Umm can you tell me how to do that? 

---

Edit:
I'm not sure if you meant something like this but here is the quest in the .json file:
![screenshot_20160412193528](https://cloud.githubusercontent.com/assets/8471727/14469619/da46ce60-00e5-11e6-8c38-a79c9b755e29.png)

**Comment by mobehun** [comment]
So i think I have managed to figure out what's going on. I was trying to use bq_standard:retrieval to mage a fluid retrieval quest instead of bq_standard:fluid.
