### ISSUE TITLE
Crash on startup: "java.lang.NoClassDefFoundError: betterquesting/api/network/IPacketHandler"

### ISSUE THREAD

**Issue by Twisted-Code** [Funwayguy/StandardQuestingPack#92]
https://gist.github.com/macks2008/4040dfbf9d4ba942f4e065f5c6463caf
all I did was try to install this like any other mod. Betterquesting is installed on both client and server, but both crash on startup

**Comment by Twisted-Code** [comment]
hmm... I think I might've had either a bad download or a wrong version. If I use the jar downloaded by the Twitch client, as opposed to downloading and installing manually as I did when I encountered this crash, the client initializes without issue. Probably safe to disregard this, though I do wonder what precisely caused it to crash in the first place...
I'll close this issue, conditionally dependent on not having any further crashes as I set up my server to use the mod.

**Comment by Twisted-Code** [comment]
Damn, I was afraid I might've closed this prematurely. My server crashed when I tried to connect to it for the first time after installing the mod
`Description: Exception in server tick loop

java.lang.NoClassDefFoundError: betterquesting/api2/utils/ParticipantInfo`
Full crash report available via this link: [crash-2019-09-20_09.09.24-server.txt](https://gist.github.com/macks2008/0f80f566a3cdf1b9044978efe142c5ff)

**Comment by Twisted-Code** [comment]
the same thing happens if I open a world in single player. Apparently it has nothing to do with any of the server-side mods I have: [crash-2019-09-20_09.18.39-server.txt](https://gist.github.com/macks2008/92262ef901eaba5a6ea98ee2e043e184)

**Comment by Funwayguy** [comment]
Got to update the base mod again. I've been changing a lot of small things out which breaks compatability in a few places like this

**Comment by Twisted-Code** [comment]
I understand. I'll give it a try when I get a chance. Until then, let's leave this open, just in case? I'll close it myself if everything works 😄

**Comment by Twisted-Code** [comment]
It worked. Closing!
