### ISSUE TITLE
Organization of Quests not the same on server

### ISSUE THREAD

**Issue by Gamerbolts** [Funwayguy/StandardQuestingPack#93]
Hi, I have been creating a rather large quest line. Each Mod has its own tab in the book. I have it all sorted and it works on client, however when I go onto the server everything is disorganized. I am not sure why the files are the same.

Here is my DefaultQuests file which is the same as the QuestDatabase on the server
https://www.dropbox.com/s/odpx9dpllpwc0rz/DefaultQuests.json?dl=0

Any help is appreciated. The way I have the quests organized is important to the way I want the modpack to be viewed so i hope you are able to fix it. Thank you!

**Comment by Funwayguy** [comment]
Can you provide screenshots of the difference between client and server?

**Comment by Gamerbolts** [comment]
Yep sure thing

This is my Client
![image](https://user-images.githubusercontent.com/20451601/66432660-360abf00-e9e4-11e9-94e8-de1a3765b2a2.png)

This is my Server
![image](https://user-images.githubusercontent.com/20451601/66432986-ed073a80-e9e4-11e9-8dd8-2baa1fbee5bd.png)

**Comment by Funwayguy** [comment]
I think I know why this happened. The new partial sync isn't accounting for the sort order of chapters. I might be able to send out a fix later today or tomorrow for this.

**Comment by Gamerbolts** [comment]
Awesome, ty :)
