### ISSUE TITLE
Crash when switching themes.

### ISSUE THREAD

**Issue by Slowwloriss** [Funwayguy/StandardQuestingPack#94]
I only pressed quest key, went to themes tab, clicked on a theme. Crashed. When reload the theme has changed to that i clicked.

Version of mods:
BQ 3.5.314
StandardExpansion 3.4.169

Crashlog with mods used
[LINK](https://pastebin.com/uvRz2ycs)

**Comment by Lgmrszd** [comment]
Can confirm this with BQ 3.5.314 (both 3.4.168 and 3.4.169 of StandardExpansion were tested)

**Comment by Funwayguy** [comment]
Was fixed in builds 315 & 316
