### ISSUE TITLE
"Potential Problem Found" Report

### ISSUE THREAD

**Issue by homeskilllet4** [Funwayguy/StandardQuestingPack#95]
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2019-12-28 18:03:02 PST
Description: Error executing task

java.util.concurrent.ExecutionException: java.lang.ArithmeticException: / by zero
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at net.minecraft.util.Util.runTask(SourceFile:531)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1088)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ArithmeticException: / by zero
    at bq_standard.client.gui.GuiLootChest.initPanel(GuiLootChest.java:44)
    at betterquesting.api2.client.gui.GuiScreenCanvas.initGui(GuiScreenCanvas.java:120)
    at net.minecraft.client.gui.GuiScreen.setWorldAndResolution(GuiScreen.java:478)
    at net.minecraft.client.Minecraft.displayGuiScreen(Minecraft.java:1018)
    at bq_standard.network.handlers.NetLootClaim.onClient(NetLootClaim.java:59)
    at bq_standard.network.handlers.NetLootClaim$$Lambda$2619/219168240.accept(Unknown Source)
    at betterquesting.network.PacketQuesting$HandleClient.lambda$onMessage$0(PacketQuesting.java:114)
    at betterquesting.network.PacketQuesting$HandleClient$$Lambda$3398/96481813.run(Unknown Source)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at net.minecraft.util.Util.runTask(SourceFile:529)
    ... 9 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 785541136 bytes (749 MB) / 3887595520 bytes (3707 MB) up to 6127878144 bytes (5844 MB)
  JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6573m -Xms256m -XX:PermSize=256m
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2847 134 mods loaded, 134 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                            | Version                   | Source                                            | Signature                                |
       |:------ |:----------------------------- |:------------------------- |:------------------------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft                     | 1.12.2                    | minecraft.jar                                     | None                                     |
       | LCHIJA | mcp                           | 9.42                      | minecraft.jar                                     | None                                     |
       | LCHIJA | FML                           | 8.0.99.99                 | forge-1.12.2-14.23.5.2847.jar                     | None                                     |
       | LCHIJA | forge                         | 14.23.5.2847              | forge-1.12.2-14.23.5.2847.jar                     | None                                     |
       | LCHIJA | itemphysic                    | 1.4.0                     | minecraft.jar                                     | None                                     |
       | LCHIJA | ivtoolkit                     | 1.3.3-1.12                | minecraft.jar                                     | None                                     |
       | LCHIJA | otgcore                       | 1.12.2 - v7               | minecraft.jar                                     | None                                     |
       | LCHIJA | openmodscore                  | 0.12.2                    | minecraft.jar                                     | None                                     |
       | LCHIJA | foamfixcore                   | 7.7.4                     | minecraft.jar                                     | None                                     |
       | LCHIJA | akashictome                   | 1.2-12                    | AkashicTome-1.2-12.jar                            | None                                     |
       | LCHIJA | crafttweaker                  | 4.1.20                    | CraftTweaker2-1.12-4.1.20.jar                     | None                                     |
       | LCHIJA | mtlib                         | 3.0.6                     | MTLib-3.0.6.jar                                   | None                                     |
       | LCHIJA | modtweaker                    | 4.0.17                    | modtweaker-4.0.17.jar                             | None                                     |
       | LCHIJA | jei                           | 4.15.0.293                | jei_1.12.2-4.15.0.293.jar                         | None                                     |
       | LCHIJA | ctm                           | MC1.12.2-1.0.1.30         | CTM-MC1.12.2-1.0.1.30.jar                         | None                                     |
       | LCHIJA | chisel                        | MC1.12.2-1.0.1.44         | Chisel-MC1.12.2-1.0.1.44.jar                      | None                                     |
       | LCHIJA | mantle                        | 1.12-1.3.3.55             | Mantle-1.12-1.3.3.55.jar                          | None                                     |
       | LCHIJA | quark                         | r1.6-177                  | Quark-r1.6-177.jar                                | None                                     |
       | LCHIJA | tinkersextras                 | 1.12.2-1.1.0              | TinkersExtras-1.12.2-1.1.0.jar                    | b02331787272ec3515ebe63ecdeea0d746653468 |
       | LCHIJA | tweakersconstruct             | 1.12.2-1.5.1              | tweakersconstruct-1.12.2-1.5.1.jar                | None                                     |
       | LCHIJA | twilightforest                | 3.10.1013                 | twilightforest-1.12.2-3.10.1013-universal.jar     | None                                     |
       | LCHIJA | tconstruct                    | 1.12.2-2.13.0.171         | TConstruct-1.12.2-2.13.0.171.jar                  | None                                     |
       | LCHIJA | immersiveengineering          | 0.12-92                   | ImmersiveEngineering-0.12-92.jar                  | 4cb49fcde3b43048c9889e0a3d083225da926334 |
       | LCHIJA | alternatingflux               | 0.12.2-2                  | alternatingflux-0.12.2-2.jar                      | None                                     |
       | LCHIJA | applecore                     | 3.2.0                     | AppleCore-mc1.12.2-3.2.0.jar                      | None                                     |
       | LCHIJA | reborncore                    | 3.16.4.478                | RebornCore-1.12.2-3.16.4.478-universal.jar        | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
       | LCHIJA | techreborn                    | 2.24.3.1043               | TechReborn-1.12.2-2.24.3.1043-universal.jar       | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
       | LCHIJA | betterwithmods                | 1.12-2.3.20-1027          | BetterWithMods-1.12-2.3.20-1027.jar               | None                                     |
       | LCHIJA | appleskin                     | 1.0.9                     | AppleSkin-mc1.12-1.0.9.jar                        | None                                     |
       | LCHIJA | autoreglib                    | 1.3-32                    | AutoRegLib-1.3-32.jar                             | None                                     |
       | LCHIJA | betteradvancements            | 0.1.0.77                  | BetterAdvancements-1.12.2-0.1.0.77.jar            | None                                     |
       | LCHIJA | betterbuilderswands           | 0.11.1                    | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar   | None                                     |
       | LCHIJA | betterquesting                | 3.5.319                   | BetterQuesting-3.5.319.jar                        | None                                     |
       | LCHIJA | betterwithengineering         | 1.2                       | BetterWithEngineering-1.6.jar                     | None                                     |
       | LCHIJA | betterwithlib                 | ${version}                | BetterWithLib-1.12-1.5.jar                        | None                                     |
       | LCHIJA | bibliocraft                   | 2.4.5                     | BiblioCraft[v2.4.5][MC1.12.2].jar                 | None                                     |
       | LCHIJA | openterraingenerator          | v6                        | OpenTerrainGenerator-1.12.2 - v6.jar              | e9f7847a78c5342af5b0a9e04e5abc0b554d69e0 |
       | LCHIJA | biomebundle                   | 5.1                       | Biome_Bundle-1.12.2-v6.1.jar                      | None                                     |
       | LCHIJA | ceramics                      | 1.12-1.3.7                | Ceramics-1.12-1.3.7.jar                           | None                                     |
       | LCHIJA | chameleon                     | 1.12-4.1.3                | Chameleon-1.12-4.1.3.jar                          | None                                     |
       | LCHIJA | chancecubes                   | 1.12.2-4.1.0.300          | ChanceCubes-1.12.2-4.1.0.300.jar                  | None                                     |
       | LCHIJA | conarm                        | 1.2.5.3                   | conarm-1.12.2-1.2.5.3.jar                         | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
       | LCHIJA | controlling                   | 3.0.7                     | Controlling-3.0.7.jar                             | None                                     |
       | LCHIJA | cookingforblockheads          | 6.4.71                    | CookingForBlockheads_1.12.2-6.4.71.jar            | None                                     |
       | LCHIJA | ctgui                         | 1.0.0                     | CraftTweaker2-1.12-4.1.20.jar                     | None                                     |
       | LCHIJA | crafttweakerjei               | 2.0.3                     | CraftTweaker2-1.12-4.1.20.jar                     | None                                     |
       | LCHIJA | creeperconfetti               | 1.4.2                     | creeperconfetti-1.4.2.jar                         | None                                     |
       | LCHIJA | cucumber                      | 1.1.3                     | Cucumber-1.12.2-1.1.3.jar                         | None                                     |
       | LCHIJA | custommainmenu                | 2.0.9                     | CustomMainMenu-MC1.12.2-2.0.9.jar                 | None                                     |
       | LCHIJA | forestry                      | 5.8.2.409                 | forestry_1.12.2-5.8.2.409.jar                     | None                                     |
       | LCHIJA | divergentunderground          | 0.64.0                    | Divergent-Underground-1.12-0.64.0.jar             | None                                     |
       | LCHIJA | dungeontactics                | DT-0.16.6                 | DungeonTactics-1.12.2-0.16.6.jar                  | None                                     |
       | LCHIJA | endercore                     | 1.12.2-0.5.73             | EnderCore-1.12.2-0.5.73.jar                       | None                                     |
       | LCHIJA | enderio                       | 5.1.52                    | EnderIO-base-1.12.2-5.1.52.jar                    | None                                     |
       | LCHIJA | enderiobase                   | 5.1.52                    | EnderIO-base-1.12.2-5.1.52.jar                    | None                                     |
       | LCHIJA | enderioconduits               | 5.1.52                    | EnderIO-conduits-1.12.2-5.1.52.jar                | None                                     |
       | LCHIJA | enderiopowertools             | 5.1.52                    | EnderIO-conduits-1.12.2-5.1.52.jar                | None                                     |
       | LCHIJA | refinedstorage                | 1.6.15                    | refinedstorage-1.6.15.jar                         | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
       | LCHIJA | enderioconduitsrefinedstorage | 5.1.52                    | EnderIO-conduits-refinedstorage-1.12.2-5.1.52.jar | None                                     |
       | LCHIJA | enderiointegrationforestry    | 5.1.52                    | EnderIO-integration-forestry-1.12.2-5.1.52.jar    | None                                     |
       | LCHIJA | exchangers                    | 1.12.2-2.8                | Exchangers-1.12.2-2.8.jar                         | 4ffa87db52cf086d00ecc4853a929367b1c39b5c |
       | LCHIJA | externaltweaker               | 0.3                       | externaltweaker-1.12-0.3.jar                      | None                                     |
       | LCHIJA | minerva                       | 1.0.13                    | minerva-library-1.0.13.jar                        | b851b8b7c7f4d8d0e910ff27618150ba80c026ec |
       | LCHIJA | extraalchemy                  | 0.5.2                     | extraalchemy-0.5.2.jar                            | b851b8b7c7f4d8d0e910ff27618150ba80c026ec |
       | LCHIJA | fastleafdecay                 | v14                       | FastLeafDecay-v14.jar                             | None                                     |
       | LCHIJA | foamfix                       | 0.10.10-1.12.2            | foamfix-0.10.10-1.12.2.jar                        | None                                     |
       | LCHIJA | ftbbackups                    | 1.1.0.1                   | FTBBackups-1.1.0.1.jar                            | None                                     |
       | LCHIJA | ftblib                        | 5.4.4.5                   | FTBLib-5.4.4.5.jar                                | None                                     |
       | LCHIJA | ftbutilities                  | 5.4.0.124                 | FTBUtilities-5.4.0.124.jar                        | None                                     |
       | LCHIJA | itemfilters                   | 1.0.3.12                  | ItemFilters-1.0.3.12.jar                          | None                                     |
       | LCHIJA | ftbquests                     | 1.8.0.237                 | FTBQuests-1.8.0.237.jar                           | None                                     |
       | LCHIJA | ftbmoney                      | 1.1.0.42                  | FTBMoney-1.1.0.42.jar                             | None                                     |
       | LCHIJA | waila                         | 1.8.26                    | Hwyla-1.8.26-B41_1.12.2.jar                       | None                                     |
       | LCHIJA | immersivecables               | 1.3.2                     | ImmersiveCables-1.12.2-1.3.2.jar                  | None                                     |
       | LCHIJA | immersivepetroleum            | 1.1.9                     | immersivepetroleum-1.12.2-1.1.9.jar               | None                                     |
       | LCHIJA | immersivetech                 | 1.3.10                    | immersivetech-1.12-1.3.10.jar                     | None                                     |
       | LCHIJA | infernalmobs                  | 1.7.6                     | InfernalMobs-1.12.2.jar                           | None                                     |
       | LCHIJA | inventorytweaks               | 1.63+release.109.220f184  | InventoryTweaks-1.63.jar                          | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
       | LCHIJA | ironbackpacks                 | 1.12.2-3.0.8-12           | IronBackpacks-1.12.2-3.0.8-12.jar                 | None                                     |
       | LCHIJA | ironchest                     | 1.12.2-7.0.67.844         | ironchest-1.12.2-7.0.72.847.jar                   | None                                     |
       | LCHIJA | jeibees                       | 0.9.0.5                   | jeibees-0.9.0.5-mc1.12.2.jar                      | None                                     |
       | LCHIJA | journeymap                    | 1.12.2-5.5.6              | journeymap-1.12.2-5.5.6.jar                       | None                                     |
       | LCHIJA | jeresources                   | 0.9.2.60                  | JustEnoughResources-1.12.2-0.9.2.60.jar           | None                                     |
       | LCHIJA | levelup2                      | ${version}                | Level Up! 2-1.1.23-1.12.jar                       | None                                     |
       | LCHIJA | libraryex                     | 1.0.12                    | LibraryEx-1.12.2-1.0.12.jar                       | None                                     |
       | LCHIJA | login_shield                  | 1.12.2-3-g7c6e7ac         | Login_Shield-1.12.2-3-g7c6e7ac.jar                | None                                     |
       | LCHIJA | lunatriuscore                 | 1.2.0.42                  | LunatriusCore-1.12.2-1.2.0.42-universal.jar       | None                                     |
       | LCHIJA | moartinkers                   | 0.6.0                     | moartinkers-0.6.0.jar                             | None                                     |
       | LCHIJA | mousetweaks                   | 2.10                      | MouseTweaks-2.10-mc1.12.2.jar                     | None                                     |
       | LCHIJA | netherportalfix               | 5.3.17                    | NetherPortalFix_1.12.1-5.3.17.jar                 | None                                     |
       | LCHIJA | nmsot                         | 1.2.2-mc1.12.2            | NoMobSpawningOnTrees-1.2.2-mc1.12.2.jar           | None                                     |
       | LCHIJA | openmods                      | 0.12.2                    | OpenModsLib-1.12.2-0.12.2.jar                     | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
       | LCHIJA | openblocks                    | 1.8.1                     | OpenBlocks-1.12.2-1.8.1.jar                       | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
       | LCHIJA | oreexcavation                 | 1.4.143                   | OreExcavation-1.4.143.jar                         | None                                     |
       | LCHIJA | patchouli                     | 1.0-20                    | Patchouli-1.0-20.jar                              | None                                     |
       | LCHIJA | pickletweaks                  | 2.1.3                     | PickleTweaks-1.12.2-2.1.3.jar                     | None                                     |
       | LCHIJA | placebo                       | 1.6.0                     | Placebo-1.12.2-1.6.0.jar                          | None                                     |
       | LCHIJA | portablecrafting              | @VERSION@                 | PortableCrafting-1.12.2-1.0.2.jar                 | None                                     |
       | LCHIJA | potioncore                    | 1.8_for_1.12.2            | PotionCore-1.8_for_1.12.2.jar                     | None                                     |
       | LCHIJA | questbook                     | 3.1.1-1.12                | questbook-3.1.1-1.12.jar                          | None                                     |
       | LCHIJA | reccomplex                    | 1.4.8.2                   | RecurrentComplex-1.4.8.2.jar                      | None                                     |
       | LCHIJA | repurpose                     | 1.0.0.19                  | Repurpose-1.0.0.19.jar                            | None                                     |
       | LCHIJA | resourceloader                | 1.5.3                     | ResourceLoader-MC1.12.1-1.5.3.jar                 | d72e0dd57935b3e9476212aea0c0df352dd76291 |
       | LCHIJA | signals                       | 1.4.1-30                  | Signals-1.12.2-1.4.1-30-universal.jar             | None                                     |
       | LCHIJA | soundfilters                  | 0.11_for_1.12             | SoundFilters-0.11_for_1.12.jar                    | None                                     |
       | LCHIJA | spiceoflife                   | 1.3.12                    | SpiceOfLife-mc1.12-1.3.12.jar                     | None                                     |
       | LCHIJA | stackie                       | 1.6.0.48                  | Stackie-1.12.2-1.6.0.48-universal.jar             | None                                     |
       | LCHIJA | bq_standard                   | 3.4.171                   | StandardExpansion-3.4.171.jar                     | None                                     |
       | LCHIJA | stepup                        | 1.0.2-mc1.10-1.12.2       | StepUp-1.0.2-mc1.10-1.12.jar                      | None                                     |
       | LCHIJA | storagedrawers                | 1.12.2-5.4.0              | StorageDrawers-1.12.2-5.4.0.jar                   | None                                     |
       | LCHIJA | surge                         | 2.0.77                    | Surge-1.12.2-2.0.77.jar                           | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | thebomplugin                  | 1.12-0.2.3                | thebomplugin-1.12-0.2.3.jar                       | None                                     |
       | LCHIJA | tinkeredhegemony              | @VERSION@                 | TinkeredHegemony-0.2.1.jar                        | None                                     |
       | LCHIJA | tcomplement                   | 1.12.2-0.4.3              | TinkersComplement-1.12.2-0.4.3.jar                | None                                     |
       | LCHIJA | tinkersjei                    | 1.2                       | tinkersjei-1.2.jar                                | None                                     |
       | LCHIJA | tinkertoolleveling            | 1.12.2-1.1.0.DEV.b23e769  | TinkerToolLeveling-1.12.2-1.1.0.jar               | None                                     |
       | LCHIJA | tombmanygraves                | 1.12-4.2.0                | TombManyGraves-1.12-4.2.0.jar                     | None                                     |
       | LCHIJA | vanillafix                    | 1.0.10-SNAPSHOT           | VanillaFix-1.0.10-99.jar                          | None                                     |
       | LCHIJA | vanillafoodpantry             | 4.3.1                     | vanillafoodpantry-mc1.12.2-4.3.1.jar              | None                                     |
       | LCHIJA | variedcommodities             | 1.12.2                    | VariedCommodities_1.12.2(21nov19).jar             | None                                     |
       | LCHIJA | veinminer                     | 0.38.2                    | VeinMiner-1.12-0.38.2.647+b31535a.jar             | None                                     |
       | LCHIJA | veinminermodsupport           | 0.38.2                    | VeinMiner-1.12-0.38.2.647+b31535a.jar             | None                                     |
       | LCHIJA | vials                         | 1.2.1.5                   | Vials-MC1.12-1.2.1.5.jar                          | None                                     |
       | LCHIJA | vc                            | 5.9.13                    | ViesCraft-1.12.2-5.9.13.jar                       | None                                     |
       | LCHIJA | vtweaks                       | 2.0.5                     | VTweaks-1.12.2-2.0.5.jar                          | None                                     |
       | LCHIJA | waterstrainer                 | 3.2.0                     | WaterStrainer-1.12-3.2.0.jar                      | None                                     |
       | LCHIJA | wawla                         | 2.5.273                   | Wawla-1.12.2-2.5.273.jar                          | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | waystones                     | 4.0.72                    | Waystones_1.12.2-4.0.72.jar                       | None                                     |
       | LCHIJA | worldprimer                   | 0.6.0-dev.20190814.220944 | worldprimer-1.12.2-0.6.0-dev.20190814.220944.jar  | 2b03e1423915a189b8094816baa18f239d576dff |
       | LCHIJA | orelib                        | 3.6.0.1                   | OreLib-1.12.2-3.6.0.1.jar                         | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCHIJA | reauth                        | 3.6.0                     | reauth-3.6.0.jar                                  | daba0ec4df71b6da841768c49fb873def208a1e3 |
       | LCHIJA | survivalist                   | 2.1.6                     | Survivalist-1.12.2-2.1.6.jar                      | None                                     |
       | LCHIJA | techreborn_compat             | 1.0.0                     | TechReborn-ModCompatibility-1.12.2-1.3.2.64.jar   | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
       | LCHIJA | primal_tech                   | 0.3.5                     | PrimalTech-0.3.5.jar                              | None                                     |
  Loaded coremods (and transformers): Quark Plugin (Quark-r1.6-177.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
                                        squeek.applecore.asm.TransformerModuleHandler
                                      CTMCorePlugin (CTM-MC1.12.2-1.0.1.30.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      OTGCorePlugin (OTG-Core.jar)
                                        com.pg85.otg.forge.asm.OTGClassTransformer
                                      OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
                                        openmods.core.OpenModsClassTransformer
                                      EnderCorePlugin (EnderCore-1.12.2-0.5.73-core.jar)
                                        com.enderio.core.common.transform.EnderCoreTransformer
                                        com.enderio.core.common.transform.SimpleMixinPatcher
                                      IELoadingPlugin (ImmersiveEngineering-core-0.12-92.jar)
                                        blusunrize.immersiveengineering.common.asm.IEClassTransformer
                                      LoadingPlugin (BetterWithLib-1.12-1.5.jar)
                                        betterwithmods.library.core.ClassTransformer
                                      Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                        
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.10-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
                                        lumien.resourceloader.asm.ClassTransformer
                                      SurgeLoadingPlugin (Surge-1.12.2-2.0.77.jar)
                                        
                                      IvToolkit (IvToolkit-1.3.3-1.12.jar)
                                        
                                      ItemPatchingLoader (ItemPhysic Lite 1.3.7 mc1.12.2.jar)
                                        com.creativemd.itemphysic.ItemTransformer
  GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 441.66' Renderer: 'GeForce RTX 2070/PCIe/SSE2'
  OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
  Pulsar/tconstruct loaded Pulses: - TinkerCommons (Enabled/Forced)
                                   - TinkerTools (Enabled/Not Forced)
                                   - TinkerHarvestTools (Enabled/Forced)
                                   - TinkerMeleeWeapons (Enabled/Forced)
                                   - TinkerRangedWeapons (Enabled/Forced)
                                   - TinkerModifiers (Enabled/Forced)
                                   - TinkerSmeltery (Enabled/Not Forced)
                                   - TinkerOredict (Enabled/Forced)
                                   - TinkerIntegration (Enabled/Forced)
                                   - TinkerFluids (Enabled/Forced)
                                   - TinkerMaterials (Enabled/Forced)
                                   - TinkerModelRegister (Enabled/Forced)
                                   - wailaIntegration (Enabled/Not Forced)
                                   - quarkIntegration (Enabled/Not Forced)
  Pulsar/tcomplement loaded Pulses: - ModuleCommons (Enabled/Forced)
                                    - ModuleMelter (Enabled/Not Forced)
                                    - ModuleArmor (Enabled/Not Forced)
                                    - ModuleSteelworks (Enabled/Not Forced)
                                    - CeramicsPlugin (Enabled/Not Forced)
                                    - ChiselPlugin (Enabled/Not Forced)
                                    - ToolLevelingPlugin (Enabled/Not Forced)
                                    - Oredict (Enabled/Forced)
  RebornCore: Plugin Engine: 0
              RebornCore Version: 3.16.4.478
              Runtime Debofucsation 1
              RenderEngine: 0
  Ender IO: No known problems detected.
            
            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
            !!!You are looking at the diagnostics information, not at the crash.       !!!
            !!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  forestry : Modules have been disabled in the config: Crate
  Suspected Mods: Standard Expansion (bq_standard), Better Questing (betterquesting)

**Comment by Funwayguy** [comment]
a div zero crash... yea that'd do it.

I can probably get this fixed up soon-ish (maybe after New Years)

**Comment by homeskilllet4** [comment]
> a div zero crash... yea that'd do it.
> 
> I can probably get this fixed up soon-ish (maybe after New Years)

Thanks!
